# Generated by Django 5.0.4 on 2024-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='is_site',
            field=models.BooleanField(default=True),
        ),
    ]
