# Generated by Django 5.0.4 on 2024-04-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_contactmodel_is_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
