# Generated by Django 5.0.4 on 2024-04-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_contactmodel_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='course_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='course_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
